### PR TITLE
Ts esm commonjs support

### PR DESCRIPTION
**Pull request by alexfigliolia**
Hey there! I came across this repo and thought it could save a me a little time in spinning up a solution of my own. I noticed that the code is common.js now living in a mostly es-modules/typescript world. I took a sec to setup build compatibility for all three formats and figured I'd PR it if you're interested. 

When making a release to `npm`, calling `yarn build` will compile separate builds for `es-module`, `common-js`, and `typescript` projects. The distribution of the correct build to the correct project is handled through the project's `package.json` which now contains the following:
```json
{
  "files": [
    "lib",
    "dist"
  ],
  "exports": {
    ".": {
      "import": "./dist/mjs/index.js",
      "require": "./dist/cjs/index.js",
      "types": "./dist/types/index.d.ts"
    }
  },
  "main": "dist/cjs/index.js",
  "module": "dist/mjs/index.js",
  "types": "dist/types/index.d.ts"
```

You'll notice in the "files" declaration, I'm now serving both the generated `dist` directory as well as the source files.

### CODE REVIEW

**Comment by alexfigliolia** [comment]
Apologies by the way for the large diff, I had to switch linters and figured I'd add formatting while I was at it. To summarize the necessary portions of the changes:

1. I ported the `lib/gzip-static` module over to typescript. This required no logical changes, but a few type-anotations
2. I ported the `test/support/http` module over to typescript. This did require refactoring prototypal inheritance over to class based. I could have ignored the typescript errors, but I figured I spare the codebase a bunch of `// @ts-ignore`'s.
3. Added a typescript-compatible linter
4. Added a build-script for compiling CJS, ESM, and types
5. Modified the package.json to distribute the correct builds based on the installers project

A few things I didn't touch:
1. I didn't modify any of the testing logic, I allowed eslint to format the file though
2. I didn't modify any of the fixtures. After converting the code to typescript, all of the tests ran perfectly. Why fix what's not broken lol

**Comment by pirxpilot** [comment]
Thanks - but I'd rather not.

This is a server-only module. I will rewrite it as ESM at some point but I do not really see any reason to increasing bundle size to have both formats exported (since one can `import` common JS module in ESM code). I will change a linter at some point but probably to something modern and not `eslint`.

I admit those are personal preferences. Goes without saying you are most welcome to use your fork.

**Comment by alexfigliolia** [comment]
Smart to close, there required an entry-point extension fix required to properly release. If you change your mind I'll reopen

**Comment by alexfigliolia** [comment]
(PSA) 

On the topic of ESM/CJS, projects do exist where once you convert to ESM, CJS projects will break and be locked into a lower major version of your package. It's unfortunate, but does exist [see Chalk's decision to support common.js then ESM](https://github.com/chalk/chalk/issues?q=is%3Aissue+es+modules). All CJS projects using TypeScript broke (this was thousands of open source/production repos) and were locked on a major version below the latest release for about 3 years.

**Comment by pirxpilot** [comment]
Yup. That's why I'd wait for Node 24 LTS [supporting sync ESM require without experimental flag](https://github.com/nodejs/node/pull/55085).

**Pull request closed without merging**
